apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: demo-app
    server: https://kubernetes.default.svc
  source:
    path: argo-cd/apps
    repoURL: https://github.com/pratheeshrussell-qb/kubernetes-session
    targetRevision: argocd
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true