apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  # this will be replaced via patch in local overlay
  local:
    path: /var/local-path-provisioner/postgres_data
  persistentVolumeReclaimPolicy: Retain