apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  storageClassName: standard
  # volumeName: postgres-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi